name: Generate SS Links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 重要！必须关闭凭证持久化

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        PHP_SESSION_ID: ${{ secrets.PHP_SESSION_ID }}
        AES_KEY: ${{ secrets.AES_KEY }}
        AES_IV: ${{ secrets.AES_IV }}
      run: |
        python ss_generator.py
        # 重命名生成的文件
        mv ss_links.txt ss.txt

    - name: Commit SS links
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ss.txt
        git commit -m "Update SS links [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push
