name: Generate SS Links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 关键修改点：每小时运行一次

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 关键修复点
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        PHP_SESSION_ID: ${{ secrets.PHP_SESSION_ID }}
        AES_KEY: ${{ secrets.AES_KEY }}
        AES_IV: ${{ secrets.AES_IV }}
      run: |
        python ss_generator.py

    - name: Commit SS links
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git add ss.txt
        git commit -m "Update SS links [$(date +'%Y-%m-%d %H:%M:%S')]"
        git pull --rebase origin main
        git push origin HEAD:main
